# Use the correct base image
FROM python:3.11.9-bookworm

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN python -m venv venv && \
    cat venv/pyvenv.cfg && \
    . venv/bin/activate && \
    pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Make the start script executable
RUN chmod +x start.sh

# Run the start script
CMD ["./start.sh"]
